import React,{useEffect,useRef,useState} from 'react'
import {api} from '../../api.js'
import {Chip,Panel} from '../../components/UI.jsx'
const PRESETS={height:'A technician was working on scaffolding at height without being connected to fall protection.',energy:'An operator opened a high-pressure bypass valve before verifying zero energy and lockout-tagout isolation.',line:'A worker walked beneath a suspended load during a crane lifting operation.'}
const SPEECH={'English':'en-IN','हिन्दी (Hindi)':'hi-IN','অসমীয়া (Assamese)':'as-IN','বাংলা (Bengali)':'bn-IN','ગુજરાતી (Gujarati)':'gu-IN','ಕನ್ನಡ (Kannada)':'kn-IN','മലയാളം (Malayalam)':'ml-IN','मराठी (Marathi)':'mr-IN','ଓଡ଼ିଆ (Odia)':'or-IN','ਪੰਜਾਬੀ (Punjabi)':'pa-IN','தமிழ் (Tamil)':'ta-IN','తెలుగు (Telugu)':'te-IN','اردو (Urdu)':'ur-IN','नेपाली (Nepali)':'ne-NP','संस्कृत (Sanskrit)':'sa-IN','कोंकणी (Konkani)':'kok-IN','کٲشُر (Kashmiri)':'ks-IN','سنڌي (Sindhi)':'sd-IN','बोडो (Bodo)':'brx-IN','डोगरी (Dogri)':'doi-IN','मैथिली (Maithili)':'mai-IN','মৈতৈলোন (Meitei / Manipuri)':'mni-IN'}
const tr=(T,k,f)=>T?.[k]||f
export default function EmployeeDashboard({T,data,site,language,profile}){
 const [tab,setTab]=useState('home'),[step,setStep]=useState(1),[obs,setObs]=useState(''),[result,setResult]=useState(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[listening,setListening]=useState(false),[interim,setInterim]=useState(''),[location,setLocation]=useState('Main operating area'),[danger,setDanger]=useState(false),[reports,setReports]=useState([]),[reportsLoading,setReportsLoading]=useState(false),[photoData,setPhotoData]=useState(null),[photoName,setPhotoName]=useState(''),[emergencyContact,setEmergencyContact]=useState(null)
 const recognitionRef=useRef(null), voiceStopRef=useRef(false)
 useEffect(()=>{api.getEmergencyContact().then(setEmergencyContact).catch(()=>setEmergencyContact(null))},[])
 useEffect(()=>()=>{voiceStopRef.current=true;recognitionRef.current?.stop();window.speechSynthesis?.cancel()},[])
 useEffect(()=>{if(tab==='reports'){setReportsLoading(true);api.getMyReports().then(r=>setReports(r.rows||[])).catch(e=>setMessage(e.message||'Could not load your reports.')).finally(()=>setReportsLoading(false))}},[tab])
 function startReport(immediate=false){setTab('report');setStep(1);setObs('');setResult(null);setPhotoData(null);setPhotoName('');setDanger(immediate);setMessage(immediate?'Immediate danger selected. Stop the activity if safe and contact your supervisor or HSE team.':'')}
 function handlePhoto(e){const file=e.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setMessage('Please choose a JPG, PNG, or WebP image.');e.target.value='';return}if(file.size>5*1024*1024){setMessage('Please choose an image smaller than 5 MB.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>{setPhotoData(String(reader.result));setPhotoName(file.name);setMessage('')};reader.onerror=()=>setMessage('The picture could not be read. Please try another image.');reader.readAsDataURL(file)}
 function removePhoto(){setPhotoData(null);setPhotoName('')} 
 function voice(){
  setMessage('');
  const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
  if(!SR)return setMessage('Voice transcription is not supported here. Please use Chrome or Edge.');
  if(listening){voiceStopRef.current=true;recognitionRef.current?.stop();setListening(false);setInterim('');return}
  voiceStopRef.current=false;
  const create=()=>{
    const r=new SR();r.lang=SPEECH[language]||'en-IN';r.continuous=true;r.interimResults=true;
    r.onstart=()=>setListening(true);
    r.onresult=e=>{let fin='',temp='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;e.results[i].isFinal?fin+=t+' ':temp+=t}if(fin.trim())setObs(v=>`${v}${v&&!v.endsWith(' ')?' ':''}${fin.trim()}`);setInterim(temp)};
    r.onerror=e=>{if(e.error!=='no-speech'&&e.error!=='aborted')setMessage('Microphone access was not available. Please check browser permission.');if(e.error!=='no-speech')setListening(false)};
    r.onend=()=>{recognitionRef.current=null;setInterim('');if(!voiceStopRef.current){setTimeout(()=>{if(!voiceStopRef.current)try{const next=create();recognitionRef.current=next;next.start()}catch(_){setListening(false)}},120);}}
    return r
  };
  try{const r=create();recognitionRef.current=r;r.start()}catch(_){setListening(false);setMessage('Could not start voice input. Please allow microphone access and try again.')}
 }
 function speak(text){window.speechSynthesis?.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=SPEECH[language]||'en-IN';window.speechSynthesis?.speak(u)}
 async function scan(){if(!obs.trim())return setMessage('Please describe what you saw first.');setLoading(true);setMessage('');try{setResult(await api.scan(obs));setStep(3)}catch(e){setMessage(e.message||'The safety check could not be completed.')}finally{setLoading(false)}}
 async function submit(){
  if(!obs.trim()||!result)return;
  setLoading(true);
  setMessage('');
  try{
    const r=await api.submitReport({text:obs,site,location,report_type:'Unsafe Act / Unsafe Condition / Near Miss',immediate_danger:danger,photo_data:photoData});
    setResult({...result,...r.scan});
    const email=r.alerts?.email;
    if(email?.sent){
      setMessage(`Report ${r.report.report_id} was submitted successfully. HSE has also been notified by email.`);
    }else if(email?.configured){
      setMessage(`Report ${r.report.report_id} was saved, but the HSE email could not be sent. HSE can still review it in the queue.`);
    }else{
      setMessage(`Report ${r.report.report_id} was submitted successfully. HSE has been notified in the system; email notification needs SMTP configuration.`);
    }
    setTab('reports');
  }catch(e){
    setMessage(e.message||'The report could not be submitted.');
  }finally{
    setLoading(false);
  }
}
 function speak(text){window.speechSynthesis?.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=SPEECH[language]||'en-IN';window.speechSynthesis?.speak(u)}
 const common=(data?.overview?.precursors||[]).slice(0,4),lsr=data?.lsr?.rows||[]
 return <div className="employee-dashboard">
  <div className="employee-welcome"><div><span className="eyebrow">OIL-SIF</span><h2>{tr(T,'employee_welcome','Welcome. What would you like to do?')}</h2><p>{tr(T,'employee_welcome_text','Report a safety concern by speaking or typing what you observed.')}</p></div><div className="employee-site"><span>Current facility</span><strong>{site}</strong></div></div>
  <div className="employee-actions"><button onClick={()=>startReport(false)} className="big-action primary"><span>🎙️</span><strong>Report a safety concern</strong><small>Tell us what you saw</small></button><button onClick={()=>setTab('reports')} className="big-action"><span>📋</span><strong>My reports</strong><small>See your submitted reports</small></button></div>
  <div className="employee-tabs" role="tablist"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}>🏠 Home</button><button className={tab==='report'?'active':''} onClick={()=>startReport(false)}>📝 Report concern</button><button className={tab==='reports'?'active':''} onClick={()=>setTab('reports')}>📋 My reports</button></div>
  {message&&<div className="alert-warning" role="status">{message}</div>}
  {tab==='home'&&<>
   <Panel title="🛡️ Safety at your facility" subtitle="Simple information to help you notice serious-risk conditions before work begins."><div className="employee-info-grid"><div><span>Common hazard pattern</span><strong>{common[0]?.precursor||'No pattern available'}</strong><small>Recurring pattern in the safety dataset</small></div><div><span>Life-Saving Rule</span><strong>{lsr[0]?.life_saving_rule||'Follow the applicable site rule'}</strong><small>Check the required control before starting work</small></div><div><span>Recent high-risk observations</span><strong>{(data?.overview?.recent_high_risk||[]).length}</strong><small>Awareness information only</small></div><div><span>Quick reminder</span><strong>See something unsafe? Report it.</strong><small>If someone is in immediate danger, stop work and contact HSE.</small></div></div></Panel>
   <Panel title="🚨 Immediate danger" subtitle="Use this when a person may be seriously injured or exposed to an immediate life-threatening hazard."><div className="stop-work-card"><div><strong>STOP WORK / REPORT IMMEDIATE DANGER</strong><p>Stop the activity if it is safe to do so, move away from danger, and inform your supervisor or HSE team.</p>{(emergencyContact?.hse_phone||emergencyContact?.hse_email||emergencyContact?.emergency_number)&&<div className="emergency-contact"><b>Reach HSE now</b>{emergencyContact.hse_phone&&<a href={`tel:${emergencyContact.hse_phone}`}>📞 {emergencyContact.hse_phone}</a>}{emergencyContact.hse_email&&<a href={`mailto:${emergencyContact.hse_email}`}>✉️ {emergencyContact.hse_email}</a>}{emergencyContact.emergency_number&&<a href={`tel:${emergencyContact.emergency_number}`}>🚑 Site emergency: {emergencyContact.emergency_number}</a>}</div>}</div><button className="danger-action" onClick={()=>startReport(true)}>🚨 Stop work</button></div></Panel>
   <Panel title="📚 Common safety patterns" subtitle="Select an example if you need help describing what you saw."><div className="topic-grid">{common.map((x,i)=><button key={i} onClick={()=>{startReport(false);setObs(x.precursor||'I observed an unsafe condition related to this activity.')}}><strong>{x.precursor}</strong><span>{Number(x.sif_density_pct||0).toFixed(1)}% SIF density</span><small>Use this as a reporting example</small></button>)}</div></Panel>
  </>}
  {tab==='report'&&<Panel title="📝 Report a safety concern" subtitle="Three simple steps. Describe the condition in your own words."><div className="report-email-notice" role="note"><span>✉️</span><div><strong>A copy of your report will be mailed to HSE.</strong><p>After you submit, your report is saved securely and a copy is sent to the HSE team for review and follow-up.</p></div></div>
   <div className="stepper">{[['1','Describe'],['2','Where'],['3','Check & submit']].map(([n,t],i)=><div className={step===i+1?'current':step>i+1?'done':''} key={n}><b>{step>i+1?'✓':n}</b><span>{t}</span></div>)}</div>
   {danger&&<div className="danger-banner"><strong>🚨 Immediate danger selected</strong><span>Stop the activity if safe and contact your supervisor or HSE team.</span></div>}
   {step===1&&<div className="guided-step"><h3>1. What did you see?</h3><p>Speak naturally or type a short description.</p><div className="example-buttons"><button onClick={()=>setObs(PRESETS.height)}>🧗 Working at height</button><button onClick={()=>setObs(PRESETS.energy)}>⚡ Energy isolation</button><button onClick={()=>setObs(PRESETS.line)}>🏗️ Suspended load</button></div><div className="voice-large"><button onClick={voice} className={listening?'listening':''}>{listening?'⏹ Stop listening':'🎙️ Tap to speak'}</button><span>{listening?'Listening… speak clearly.':'Your words will appear below.'}</span></div>{interim&&<div className="interim">🎙️ {interim}</div>}<textarea rows="7" value={obs} onChange={e=>setObs(e.target.value)} placeholder="Example: I saw a worker standing under a suspended load while the crane was moving it."/><div className="step-actions"><button className="btn-primary" onClick={()=>obs.trim()?setStep(2):setMessage('Please describe what you saw first.')}>Next: Location →</button></div></div>}
   {step===2&&<div className="guided-step"><h3>2. Where did it happen?</h3><p>Select the closest area. This helps HSE understand the report.</p><div className="location-grid">{['Main operating area','Drilling / production area','Maintenance area','Warehouse / depot','Access / walkway','Other'].map(x=><button className={location===x?'selected':''} onClick={()=>setLocation(x)} key={x}>{x}</button>)}</div><div className="photo-upload"><div className="photo-upload-copy"><strong>📷 Upload a picture <span>({tr(T,'optional','Optional')})</span></strong><p>{tr(T,'upload_picture_help','Add a photo of the condition or area to help HSE review the report.')}</p></div><label className="upload-button">{photoData?'Change picture':'Choose picture'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={handlePhoto} /></label>{photoData&&<div className="photo-preview"><img src={photoData} alt="Safety concern preview" /><div><strong>{photoName}</strong><button type="button" className="text-link" onClick={removePhoto}>Remove</button></div></div>}</div><div className="step-actions"><button className="btn-secondary" onClick={()=>setStep(1)}>← Back</button><button className="btn-primary" onClick={scan} disabled={loading}>{loading?'Checking…':'Check safety risk →'}</button></div></div>}
   {step===3&&<div className="guided-step"><h3>3. Check the result and submit</h3><p>AI screening is a first check. It does not replace HSE judgement.</p>{result&&<div className={`result-card ${result.evidence_level==='critical'||result.is_sif?'critical':result.evidence_level==='review'||result.evidence_level==='high'?'review':'clear'}`}><div className="result-top"><span>{result.evidence_level==='critical'?'🔴 Critical safety event detected':result.evidence_level==='high'||result.is_sif?'🟠 Potential serious-risk precursor':result.evidence_level==='review'?'🟠 Safety concern needs HSE review':'🟢 No high-consequence pattern detected'}</span><strong>{Number(result.sif_probability??result.confidence??0).toFixed(1)}% screening score</strong></div><div className="result-grid"><div><span>Life-Saving Rule</span><strong>{result.rule_name||'Not mapped'}</strong><small>{result.lsr_confidence?`${Number(result.lsr_confidence).toFixed(1)}% ML confidence`:''}</small></div><div><span>Hazard</span><strong>{result.hazard||'Safety concern'}</strong></div><div><span>Barrier to check</span><strong>{result.barrier||'Required work control'}</strong></div><div><span>Potential consequence</span><strong>{result.potential_consequence||'Potential serious injury if controls fail.'}</strong></div></div><div className="plain-language"><strong>What this means</strong><p>{result.evidence_level==='critical'?'A critical safety event pattern was detected. Stop the activity if safe and contact HSE/supervision immediately.':result.evidence_level==='high'||result.is_sif?'A serious-risk precursor was detected by the screening. Stop or isolate the activity if safe and restore the required control before continuing.':result.evidence_level==='review'?'The report describes an injury or exposure that needs HSE review. The score is a screening signal, not a diagnosis or final SIF decision.':'No explicit high-consequence pattern was detected by the initial screening. Continue following site controls and reporting procedures.'}</p><small className="screening-note">ML model: {Number(result.model_sif_probability??result.sif_probability??0).toFixed(1)}% · Rule evidence: {result.evidence_reason||'None detected'}</small><button className="btn-secondary compact" onClick={()=>speak(result.evidence_level==='critical'||result.is_sif?'A serious-risk safety pattern was detected. Please stop the activity if safe and contact HSE.':result.evidence_level==='review'?'This report describes an injury or exposure that needs HSE review.':'No explicit high-consequence pattern was detected by the initial screening.')}>🔊 Read aloud</button></div></div>}<div className="submit-summary"><span>Location</span><strong>{location}</strong></div><div className="step-actions"><button className="btn-secondary" onClick={()=>setStep(2)}>← Change details</button><button className="btn-primary" onClick={submit} disabled={loading}>{loading?'Submitting…':'✓ Submit safety report'}</button></div></div>}
  </Panel>}
  {tab==='reports'&&<Panel title="📋 My safety reports" subtitle="These reports are stored by the OIL-SIF system. HSE review status is updated from the server.">{reportsLoading?<div className="loading-state"><strong>Loading your reports…</strong></div>:reports.length?<div className="my-report-list">{reports.map((r,i)=><div className="my-report" key={r.report_id||i}><div><strong>{r.report_id}</strong><span>{r.date_of_incident||'No date'} · {r.location||'Location not specified'}</span></div><Chip tone={String(r.sif_prediction||'').toLowerCase().includes('sif')?'red':String(r.hse_review_status||'').toLowerCase().includes('pending')?'amber':'green'}>{r.hse_review_status||'Pending HSE review'}</Chip><div className="my-report-body"><b>{r.life_saving_rule||'Rule not mapped'}</b><p>{r.report_text}</p>{r.hse_decision&&<div className="review-feedback"><strong>HSE decision:</strong> {r.hse_decision}{r.corrective_action&&<><br/><strong>Corrective action:</strong> {r.corrective_action}</>}</div>}</div></div>)}</div>:<div className="empty-state"><strong>No reports yet.</strong><p>When you submit a safety concern, it will appear here.</p><button className="btn-primary compact" onClick={()=>startReport(false)}>Report a concern</button></div>}</Panel>}
 </div>
}
