import React,{useEffect,useState} from 'react'
import {api} from '../../api.js'
import {Chip,Panel} from '../../components/UI.jsx'
export default function ReportAnalysis({T,data,initialSeed,site}){
 const [search,setSearch]=useState(initialSeed||''),[status,setStatus]=useState('all'),[review,setReview]=useState('all'),[activity,setActivity]=useState('all'),[period,setPeriod]=useState('all'),[reports,setReports]=useState(data?.rows||[]),[total,setTotal]=useState(data?.total||0),[selected,setSelected]=useState(null),[activities,setActivities]=useState([]),[loading,setLoading]=useState(false),[ai,setAi]=useState(null),[decision,setDecision]=useState(''),[reason,setReason]=useState(''),[action,setAction]=useState(''),[saving,setSaving]=useState(false),[notice,setNotice]=useState('')
 useEffect(()=>{api.getActivities().then(r=>setActivities([...new Set((r.rows||[]).map(x=>x.activity_group||x.Activity).filter(Boolean))])).catch(()=>{})},[])
 useEffect(()=>{const timer=setTimeout(()=>{setLoading(true);api.getReports({...({search,status,review,activity,site}),...(periodDates(period)),limit:100}).then(r=>{setReports(r.rows||[]);setTotal(r.total||0);setSelected(s=>s&&r.rows.some(x=>x.report_id===s.report_id)?s:r.rows?.[0]||null)}).catch(()=>{setReports([]);setTotal(0)}).finally(()=>setLoading(false))},180);return()=>clearTimeout(timer)},[search,status,review,activity,period,site])
 useEffect(()=>{if(!selected)return;api.getReportDetail(selected.report_id).then(r=>{setSelected(x=>({...x,...r.report}));setDecision(r.report.hse_decision||'');setReason(r.report.hse_reason||'');setAction(r.report.corrective_action||'')}).catch(()=>{});setAi(null)},[selected?.report_id])
 function periodDates(value){if(value==='all')return {date_from:'',date_to:''};const end=new Date();const start=new Date();start.setDate(end.getDate()-Number(value)+1);return {date_from:start.toISOString().slice(0,10),date_to:end.toISOString().slice(0,10)}}
 const has=search||status!=='all'||review!=='all'||activity!=='all'||period!=='all'
 function clear(){setSearch('');setStatus('all');setReview('all');setActivity('all');setPeriod('all')}
 async function runAi(){if(!selected?.report_text)return;setAi({loading:true});try{setAi(await api.scan(selected.report_text))}catch(e){setAi({error:e.message})}}
 async function saveReview(){if(!selected||!decision)return;setSaving(true);setNotice('');try{const r=await api.saveReview(selected.report_id,decision,reason,action);setSelected(x=>({...x,hse_decision:r.decision,corrective_action:r.action,hse_reason:r.reason,hse_review_status:r.decision==='Needs More Information'?'Needs more information':'Reviewed'}));setNotice('HSE review saved successfully.');}catch(e){setNotice(e.message||'Could not save the review.')}finally{setSaving(false)}}
 async function exportCsv(){try{await api.exportReports({search,status,review,activity,site,...periodDates(period)})}catch(e){setNotice(e.message)}}
 return <div className="report-analysis-page"><div className="report-toolbar"><div><h2>Safety Report Explorer</h2><p>Search the report set and use the selected facility as the scope for live submitted reports.</p></div><div className="toolbar-actions"><button className="btn-secondary" onClick={exportCsv}>⇩ Export CSV</button>{has&&<button className="btn-secondary" onClick={clear}>Clear filters</button>}</div></div>
 <Panel title="🔎 Find reports" subtitle="Use report ID, activity, precursor, Life-Saving Rule or words from the report narrative."><div className="report-controls"><div className="search-large"><label>Search</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Example: forklift, harness, LOTO, ITA-20260910…"/></div><div><label>Risk</label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All reports</option><option value="sif">SIF potential</option><option value="non-sif">Non-SIF potential</option></select></div><div><label>Review</label><select value={review} onChange={e=>setReview(e.target.value)}><option value="all">All</option><option value="pending">Pending HSE review</option><option value="reviewed">Reviewed</option></select></div><div><label>Date</label><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">All dates</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last 12 months</option></select></div><div><label>Activity</label><select value={activity} onChange={e=>setActivity(e.target.value)}><option value="all">All activities</option>{activities.map(a=><option key={a}>{a}</option>)}</select></div></div><div className="results-summary">{loading?'Updating…':`Showing ${Math.min(reports.length,100).toLocaleString()} of ${total.toLocaleString()} reports`}</div><div className="report-list">{reports.map(r=><button className={`report-row ${selected?.report_id===r.report_id?'selected':''}`} key={r.report_id} onClick={()=>setSelected(r)}><div><strong>{r.report_id}</strong><span>{r.date_of_incident||'No date'} · {r.activity_group||'Unknown activity'}</span></div><div><span>{r.life_saving_rule||'Rule not mapped'}</span><Chip tone={String(r.sif_prediction||'').toLowerCase().includes('sif')?'red':String(r.hse_review_status||'').toLowerCase().includes('pending')?'amber':'green'}>{r.hse_review_status||r.sif_prediction||'Unknown'}</Chip></div></button>)}</div></Panel>
 {selected&&<Panel title={`📄 ${selected.report_id}`} subtitle="Review the report, AI evidence and HSE decision in one place."><div className="detail-grid"><div className="detail-facts">{[['Date',selected.date_of_incident],['Site',selected.site],['Location',selected.location],['Activity',selected.activity_group],['Precursor / hazard',selected.precursor],['Life-Saving Rule',selected.life_saving_rule],['Risk status',selected.sif_prediction],['Review status',selected.hse_review_status]].map(([a,b])=><div key={a}><span>{a}</span><strong>{b||'—'}</strong></div>)}</div><div><span className="field-label">Report narrative</span><div className="narrative-box">{selected.report_text||'No narrative available.'}</div><div className="detail-actions"><button className="btn-secondary" onClick={()=>window.speechSynthesis?.speak(new SpeechSynthesisUtterance(selected.report_text||''))}>🔊 Read aloud</button>{selected.photo_url&&<a className="btn-secondary" href={selected.photo_url} target="_blank" rel="noreferrer">📷 View photo</a>}</div></div></div>
 <div className="review-workbench"><div className="workbench-head"><div><h3>Human HSE validation</h3><p>AI supports triage; qualified HSE personnel make the final decision.</p></div><button className="btn-primary" onClick={runAi}>{ai?.loading?'Checking…':'🤖 Run AI screening'}</button></div>{ai&&!ai.loading&&!ai.error&&<div className={`ai-evidence ${ai.is_sif?'critical':'clear'}`}><div><span>AI screening</span><strong>{ai.is_sif?'Potential SIF precursor':'Non-SIF potential'}</strong></div><div><span>Confidence</span><strong>{ai.confidence}%</strong></div><div><span>Life-Saving Rule</span><strong>{ai.rule_name||'Not mapped'}</strong></div><div><span>Barrier</span><strong>{ai.barrier||'—'}</strong></div><div><span>ML models</span><strong>{ai.sif_model_backed&&ai.lsr_model_backed?'SIF + LSR ML':'ML screening available'}</strong></div></div>}{ai?.error&&<div className="alert-warning">{ai.error}</div>}
 <div className="decision-grid"><div><label>HSE decision</label><div className="decision-buttons"><button className={decision==='Confirm SIF'?'chosen danger':''} onClick={()=>setDecision('Confirm SIF')}>🔴 Confirm SIF</button><button className={decision==='Not SIF'?'chosen':''} onClick={()=>setDecision('Not SIF')}>🟢 Not SIF</button><button className={decision==='Needs More Information'?'chosen':''} onClick={()=>setDecision('Needs More Information')}>🟡 Needs more information</button></div></div><div><label>Reason / site evidence</label><textarea rows="4" value={reason} onChange={e=>setReason(e.target.value)} placeholder="What did the HSE review confirm?"/></div><div><label>Corrective action</label><textarea rows="4" value={action} onChange={e=>setAction(e.target.value)} placeholder="What action should be taken or verified?"/></div></div>{notice&&<div className="alert-success">{notice}</div>}<button className="btn-primary" onClick={saveReview} disabled={!decision||saving}>{saving?'Saving…':'✓ Save HSE review'}</button></div></Panel>}
 </div>
}
